version: '3.9'

services:
  multi_trade_ui:
    build: .
    container_name: multi_trade_ui
    ports:
      - "8082:8082"
    volumes:
      - .:/app       # Автоматичне оновлення коду
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8082 --reload
